codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      go:
        target: 88%
        threshold: 0%
        informational: false
        flags:
          - go
    patch: off

comment:
  layout: "reach, diff, files"
  require_changes: false

# Go profiles name files by import path.
fixes:
  - "github.com/pg83/s3/::"

ignore:
  - "tst/**/*"
  - "dev/**/*"
  - "**/*_test.go"
